name: Setup LLVM
description: >
  Set up a specific version of LLVM and add the command-line tools to the PATH.
author: ZhongRuoyu
inputs:
  llvm-version:
    description: Version of LLVM to use
  github-token:
    description: Token to authenticate GitHub API requests
    default: ${{ github.token }}
outputs:
  llvm-path:
    description: The absolute path to the LLVM installation
    value: ${{ steps.output.outputs.llvm-path }}

runs:
  using: composite
  steps:
    - name: Setup LLVM on Linux
      if: runner.os == 'Linux'
      run: |
        "$GITHUB_ACTION_PATH"/linux.sh
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
        SETUP_LLVM_GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: sh

    - name: Setup LLVM on macOS
      if: runner.os == 'macOS'
      run: |
        "$GITHUB_ACTION_PATH"/macos.sh
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
        SETUP_LLVM_GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: sh

    - name: Setup LLVM on Windows
      if: runner.os == 'Windows'
      run: |
        & "$env:GITHUB_ACTION_PATH/windows.ps1"
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
        SETUP_LLVM_GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: pwsh

    - name: Set output
      id: output
      run: |
        import os
        with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
          print(f"llvm-path={os.getenv('LLVM_PATH')}", file=f)
      shell: python

branding:
  icon: code
  color: yellow
