name: Setup LLVM
description: >
  Set up a specific version of LLVM and add the command-line tools to the PATH.
author: ZhongRuoyu
inputs:
  llvm-version:
    description: Version of LLVM to use
outputs:
  llvm-path:
    description: The absolute path to the LLVM installation
    value: ${{ steps.output.outputs.llvm-path }}

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      run: '${{ github.action_path }}/linux.sh'
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
      shell: sh

    - if: runner.os == 'macOS'
      run: '${{ github.action_path }}/macos.sh'
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
      shell: sh

    - if: runner.os == 'Windows'
      run: '${{ github.action_path }}/windows.ps1'
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
      shell: pwsh

    - id: output
      run: |
        import os
        with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
          print(f"llvm-path={os.getenv('LLVM_PATH')}", file=f)
      shell: python

branding:
  icon: code
  color: yellow
