name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-26.04-arm
          - macos-latest
          - windows-latest
          - windows-11-arm
        llvm-version:
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - ""
        # Earlier versions of LLVM do not have official ARM64 Linux builds.
        exclude:
          - os: ubuntu-26.04-arm
            llvm-version: 17
          - os: ubuntu-26.04-arm
            llvm-version: 18
          - os: ubuntu-26.04-arm
            llvm-version: 19
          - os: ubuntu-26.04-arm
            llvm-version: 20
      fail-fast: false
    name: Tests (${{ matrix.os }} - LLVM ${{ matrix.llvm-version || 'default' }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup LLVM
        uses: ./
        with:
          llvm-version: ${{ matrix.llvm-version }}
          github-token: ${{ github.token }}
