name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        llvm-version:
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - ""
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LLVM
        uses: ./
        with:
          llvm-version: ${{ matrix.llvm-version }}
          github-token: ${{ github.token }}
